### ISSUE TITLE
11月开始自动生成的pac 有问题

### ISSUE THREAD

**Issue by Leon406** [cdlaimin/FileList#1]
https://raw.githubusercontent.com/cdlaimin/FileList/master/PACList.pac

https://github.com/cdlaimin/FileList/commit/354569b20c67f047e0d02986c41e0f386f52c8a8

**Comment by cdlaimin** [comment]
应该是环境问题,11月我换了个服务器

**Comment by Leon406** [comment]
https://github.com/cdlaimin/FileList/commit/a7bbb4e7d6ab1c03d6d0927afb647279adc35021
12/5开始又出问题了

**Comment by cdlaimin** [comment]
> [a7bbb4e](https://github.com/cdlaimin/FileList/commit/a7bbb4e7d6ab1c03d6d0927afb647279adc35021) 12/5开始又出问题了

阿这.. 我看了其他项目生成的pac也是这样的呀
